### PR TITLE
make it build on stretch

### PR DESCRIPTION
**Pull request by mzanetti**

### CODE REVIEW

**Comment by mzanetti** [comment]
Jenkins, retest this please

**Comment by mzanetti** [comment]
Jenkins, retest this please

**Comment by mzanetti** [comment]
Jenkins, land this please

**Comment by mzanetti** [comment]
Jenkins, land this please

**Comment by mzanetti** [comment]
Jenkins, land this please

**Comment by mzanetti** [comment]
Jenkins, land this please

**Comment by mzanetti** [comment]
Jenkins, land this please

**Comment by mzanetti** [comment]
Jenkins, land this please

**Comment by t-mon** [comment]
:+1:

**Comment by mzanetti** [comment]
Jenkins, land this please

**Pull request merged**
