### PR TITLE
added upnp discovery as hardware resource

### PR DESCRIPTION
**Pull request by t-mon**
this new hardware resource allows plugins to search UPnP devices by giving a certain search target and a special userAgent (for the HTTP header).

### CODE REVIEW

**Comment by mzanetti** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/158/
Test PASSed.

**Comment by mzanetti** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/159/
Test FAILed.

**Comment by mzanetti** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/160/
Test PASSed.

**Comment by mzanetti** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/162/
Test PASSed.

**Comment by t-mon** [comment]
@mzanetti : I think this is now ready to go into the master! However, the hue plugin currently does not work, because I have no possibility to test the plugin. 
If you would update the philips plugin after the network manager pull request, that would be awesome! :question:

**Comment by mzanetti** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/169/
Test PASSed.

**Pull request merged**
