### PR TITLE
added exitActions for state based rules

### PR DESCRIPTION
**Pull request by t-mon**

### CODE REVIEW

**Comment by t-mon** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/202/
Test FAILed.

**Comment by t-mon** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/203/
Test FAILed.

**Comment by t-mon** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/204/
Test PASSed.

**Comment by t-mon** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/205/
Test PASSed.

**Comment by t-mon** [comment]
this fixes issue #99

**Comment by mzanetti** [comment]
Also add the exitactions to the tests "loadStoreConfig" (to verify they are properly stored to the config and loaded again) and "evaluateStateChange" (to verify they are executed when the state leaves)

**Comment by t-mon** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/207/
Test PASSed.

**Pull request merged**
