### PR TITLE
Api authentication

### PR DESCRIPTION
**Pull request by t-mon**

### CODE REVIEW

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/481/

**Comment by t-mon** [comment]
Jenkins, retest this please.

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/482/

**Comment by t-mon** [comment]
Jenkins, retest this please.

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/483/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/484/

**Comment by t-mon** [comment]
Jenkins, retest this please.

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/485/

**Comment by t-mon** [comment]
Jenkins, retest this please.

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/486/

**Comment by t-mon** [comment]
Jenkins, retest this please.

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/487/

**Comment by t-mon** [comment]
Jenkins, retest this please.

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/488/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/489/

**Comment by t-mon** [comment]
Jenkins, retest this please.

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/490/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/491/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/492/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/493/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/494/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/502/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/503/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/504/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/541/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/548/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/575/

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/576/

**Comment by t-mon** [comment]
Jenkins, retest this please.

**Comment by t-mon** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://guh.guru:8080/job/guh-pull-request-builder/577/

**Comment by mzanetti** [comment]
closing this. some of this made it into master in a new branch.

**Pull request closed without merging**
